IF
    OnCreation()
THEN
    RESPONSE #100
        StartTimer(77,6)
END

IF
    HPLT(Myself,15)
    !StateCheck(Myself,STATE_DEAD)
THEN
    RESPONSE #100
        ReallyForceSpellRES("AC#GRT3",Myself)  // No such index
END

IF
    HPLT(Myself,12)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        StartTimer(77,6)
        ChangeAnimationNoEffect("AC#GRTR2")  // Grautroll
END

IF
    TimerExpired(77)
THEN
    RESPONSE #100
        StartTimer(77,6)
END

