IF
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        Enemy()
END

IF
    OR(2)
        See([GOODCUTOFF.0.0.CLERIC_ALL])
        See([GOODCUTOFF.0.0.MAGE_ALL])
    Global("silence","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)  // SPIN998.SPL (Stille: 4,5 m Radius)
        SetGlobal("silence","LOCALS",1)
END

IF
    See([GOODCUTOFF])
    Global("abilities","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),TANARI_DEATH_GAZE)  // SPIN996.SPL (Todesblick)
        SetGlobal("abilities","LOCALS",1)
        Wait(1)
        ForceSpell(LastSeenBy(Myself),TANARI_PARALYZE)  // SPIN999.SPL (Lähmung)
END

IF
    See([GOODCUTOFF])
THEN
    RESPONSE #60
        AttackOneRound(LastSeenBy(Myself))
        AttackOneRound(LastSeenBy(Myself))
    RESPONSE #20
        ForceSpell(LastSeenBy(Myself),TANARI_VAMPIRIC_TOUCH)  // SPIN997.SPL (Vampirgriff)
        AttackOneRound(LastSeenBy(Myself))
    RESPONSE #15
        ForceSpell(LastSeenBy(Myself),TANARI_PARALYZE)  // SPIN999.SPL (Lähmung)
        AttackOneRound(LastSeenBy(Myself))
    RESPONSE #5
        ForceSpell(LastSeenBy(Myself),TANARI_DEATH_GAZE)  // SPIN996.SPL (Todesblick)
        AttackOneRound(LastSeenBy(Myself))
END

IF
    OR(2)
        See([0.0.0.CLERIC_ALL])
        See([0.0.0.MAGE_ALL])
    Global("silence","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)  // SPIN998.SPL (Stille: 4,5 m Radius)
        SetGlobal("silence","LOCALS",1)
END

IF
    See([ANYONE])
    CheckStatLT(LastSeenBy(Myself),1,DISABLE_CIRCLE)
    Global("abilities","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),TANARI_DEATH_GAZE)  // SPIN996.SPL (Todesblick)
        SetGlobal("abilities","LOCALS",1)
        Wait(1)
        ForceSpell(LastSeenBy(Myself),TANARI_PARALYZE)  // SPIN999.SPL (Lähmung)
END

IF
    See([ANYONE])
    CheckStatLT(LastSeenBy(Myself),1,DISABLE_CIRCLE)
THEN
    RESPONSE #70
        AttackReevaluate(LastSeenBy(Myself),30)
    RESPONSE #15
        ForceSpell(LastSeenBy(Myself),TANARI_VAMPIRIC_TOUCH)  // SPIN997.SPL (Vampirgriff)
        Wait(2)
    RESPONSE #10
        ForceSpell(LastSeenBy(Myself),TANARI_PARALYZE)  // SPIN999.SPL (Lähmung)
        Wait(2)
    RESPONSE #5
        ForceSpell(LastSeenBy(Myself),0)
        Wait(2)
END

