IF
    HitBy([ANYONE],FIRE)
    Global("NoFusion","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("NoFusion","LOCALS",1)
END

IF
    Die()
    Global("NoFusion","LOCALS",0)
THEN
    RESPONSE #100
        DisplayStringHead(Myself,71108)  // Statt zu sterben, teilt sich die Kreatur entzwei.
        CreateCreatureObjectEffect("SLIFIS02","AC#MGGOY",Myself)  // Teilungsschleim
        CreateCreatureObjectEffect("SLIFIS02","AC#MGGOY",Myself)  // Teilungsschleim
END

